name: Java Matrix

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 11, 17]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Microsoft's OpenJDK distribution
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
