name: Matrix

on:
  workflow_dispatch: 

jobs:
 matrix-jobs:
  runs-on: ${{matrix.os}}
  strategy:
      matrix:
        os:
         - ubuntu-latest
         - windows-latest
        java-version: [17,21]
  steps:
     - name: Setup java JDK
       uses: actions/setup-java@v3
       with:
         java-version: ${{ matrix.java-version}}
         distribution: microsoft
