name: Matrix with java and ubuntu

on:
  workflow_dispatch: 

jobs:
 matrix-jobs:
  runs-on: ${{matrix.os}}
  strategy:
      matrix:
        os:
         - ubuntu-latest
         - windows-latest
        java-version: [8, 11, 17]
  steps:
     - name: Setup java JDK
       uses: actions/setup-java@v3
       with:
         java-version: ${{ matrix.java-version}}
         distrubition: microsoft
